### ISSUE TITLE
Please Update V12

### ISSUE THREAD

**Issue by shrek-kurata** [KimuraYu45z/ng-loading-dialog#5]
Package "ng-loading-dialog" has an incompatible peer dependency to "@angular/cdk" (requires "^11.1.0", would install "12.0.5").
                  Package "ng-loading-dialog" has an incompatible peer dependency to "@angular/material" (requires "^11.1.0", would install "12.0.5").

**Comment by kimurayu45z** [comment]
ACK

**Comment by kimurayu45z** [comment]
https://github.com/KimuraYu45z/ng-loading-dialog/releases/tag/v12.0.5
